apiVersion: v1
name: spotinst-kubernetes-cluster-controller
description: A Helm chart for Ocean Controller
version: 1.0.98
appVersion: 1.0.80
icon: https://docs.spot.io/_media/images/spot_mark.png
keywords:
- spot
- ocean
- controller
