metrics-server:
  deployChart: false

spotinst:
  token: test
  account: test
  clusterIdentifier: test

secret:
  enabled: true
  create: true

serviceAccount:
  create: true

configMap:
  create: true

aksConnector:
  enabled: true
  acdIdentifier: test
